INSERT INTO pokedex
(name, type1, type2, health, move1, move2, move3, move4) 
VALUES 
("BULBASAUR", "GRASS", "POISON", 45, "RAZOR LEAF", "TACKLE", "GROWL", "VINE WHIP"),
("IVYSAUR", "GRASS", "POISON", 60, "RAZOR LEAF", "BODY SLAM", "CUT", "VINE WHIP"),
("VENUSAUR", "GRASS", "POISON", 80, "RAZOR LEAF", "MEGA DRAIN", "BODY SLAM", "VINE WHIP"),
("CHARMANDER", "FIRE", NULL, 39, "EMBER", "SCRATCH", "GROWL", "LEER"),
("CHARMELEON", "FIRE", NULL, 58, "FLAMETHROWER", "SLASH", "GROWL", "FIRE SPIN"), 
("CHARIZARD", "FIRE", "FLYING", 78, "FLAMETHROWER", "SLASH", "FIRE BLAST", "FIRE SPIN"), 
("SQUIRTLE", "WATER", NULL, 44, "TACKLE", "TAIL WHIP", "WATER GUN", "BUBBLE"), 
("WARTORTLE", "WATER", NULL, 59, "WATER GUN", "BITE", "BUBBLEBEAM", "TAIL WHIP"),
("BLASTOISE", "WATER", NULL, 44, "WATER GUN", "SURF", "BUBBLEBEAM", "TAIL WHIP"),
("CATERPIE", "BUG", NULL, 45, "TACKLE", "STRING SHOT", "POISON STING", NULL),
("METAPOD", "BUG", NULL, 50, "SPLASH", "HARDEN", "TACKLE", NULL),
("BUTTERFREE", "BUG", "FLYING", 60, "CONFUSION", "GUST", "STRING SHOT", "MEGA DRAIN"),
("WEEDLE", "BUG", "POISON", 40, "TACKLE", "POISON STING", "STRING SHOT", NULL),
("KAKUNA", "BUG", "POISON", 45, "SPLASH", "HARDEN", "TACKLE", NULL),
("BEEDRILL", "BUG", "POISON", 65, "PIN MISSLE", "FURY ATTACK", "MEGA DRAIN", "SWORD DANCE"),
("PIDGEY", "NORMAL", "FLYING", 40, "TACKLE", "PECK", "SAND ATTACK", NULL),
("PIDGEOTTO", "NORMAL", "FLYING", 63, "GUST", "QUICK ATTACK", "WING ATTACK", "SAND ATTACK"),
("PIDGEOT", "NORMAL", "FLYING", 83, "GUST", "WING ATTACK", "QUICK ATTACK", "SWIFT");
("RATTATA", "NORMAL", NULL, 30, "TACKLE", "TAIL WHIP", "QUICK ATTACK", NULL);
("RATICATE", "NORMAL", NULL, 55, "TACKLE", "QUICK ATTACK", "HYPER FANG", "BODY SLAM");
